### ISSUE TITLE
User should not be prompted for login when page is refreshed

### ISSUE THREAD

**Issue by gwsii** [Nordstrom/hello-retail#48]
It's not technically necessary to do that. There's a cookie that keeps you authenticated, it's just that the client code doesn't check it.

Fix would be to have AWSLogin component call authorize() and verify that the user is not authenticated before showing the login button and requiring re-authentication.

**Comment by erikerikson** [comment]
fixed yes?  link to PR?

**Comment by RobGruhl** [comment]
mostly fixed, still happens when auth expired after walking away for a while, different issue.
